# Generated by Django 3.2.20 on 2023-07-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('teacher', 'teacher'), ('student', 'student')], default='student', max_length=7, verbose_name='role'),
        ),
    ]
