# Generated by Django 3.2.20 on 2023-07-19 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_remove_courselist_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_role', models.CharField(choices=[('teacher', 'teacher'), ('student', 'student'), ('teaching assistant', 'teaching assistant')], default='student', max_length=25, verbose_name='course role')),
            ],
            options={
                'verbose_name': 'course registration list',
                'verbose_name_plural': 'course registration list',
                'ordering': ('courseID',),
            },
        ),
        migrations.CreateModel(
            name='CoursesList',
            fields=[
                ('courseID', models.CharField(default=' ', max_length=10, primary_key=True, serialize=False, verbose_name='courseID')),
                ('courseName', models.CharField(default=' ', max_length=20, verbose_name='course name')),
                ('courseDescription', models.TextField(default=' ', verbose_name='course description')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'course list',
                'verbose_name_plural': 'course list',
                'ordering': ('courseID',),
            },
        ),
        migrations.DeleteModel(
            name='CourseList',
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='courseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseslist'),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
