# Generated by Django 4.2.2 on 2023-08-13 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assignment_files',
        ),
    ]
