# Generated by Django 4.2.2 on 2023-07-26 08:11

import api.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_files',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploads/', validators=[api.validators.validate_file_extension]),
            preserve_default=False,
        ),
    ]
