# Generated by Django 4.2.2 on 2023-07-26 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_studentsubmissons_assignmentsubmission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentSubmissons',
        ),
    ]
