# Generated by Django 4.2.2 on 2023-07-27 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_assignmentsubmission_assignmentid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='assignmentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assignment'),
        ),
    ]
