# Generated by Django 3.2.20 on 2023-07-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20230719_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseslist',
            name='courseName',
            field=models.CharField(default=' ', max_length=40, verbose_name='course name'),
        ),
    ]
