# Generated by Django 4.2.2 on 2023-08-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20230801_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseslist',
            name='Syllabus_Week10',
            field=models.CharField(default='week 10 session', max_length=30, verbose_name='week 10'),
        ),
        migrations.AlterField(
            model_name='courseslist',
            name='Syllabus_Week11',
            field=models.CharField(default='week 11 session', max_length=30, verbose_name='week 11'),
        ),
        migrations.AlterField(
            model_name='courseslist',
            name='Syllabus_Week12',
            field=models.CharField(default='final exam', max_length=30, verbose_name='week 12'),
        ),
        migrations.AlterField(
            model_name='courseslist',
            name='Syllabus_Week2',
            field=models.CharField(default='week 2 session', max_length=30, verbose_name='week 2'),
        ),
        migrations.AlterField(
            model_name='courseslist',
            name='Syllabus_Week3',
            field=models.CharField(default='week 3 session', max_length=30, verbose_name='week 3'),
        ),
        migrations.AlterField(
            model_name='courseslist',
            name='Syllabus_Week4',
            field=models.CharField(default='week 4 session', max_length=30, verbose_name='week 4'),
        ),
        migrations.AlterField(
            model_name='courseslist',
            name='Syllabus_Week5',
            field=models.CharField(default='week 5 session', max_length=30, verbose_name='week 5'),
        ),
        migrations.AlterField(
            model_name='courseslist',
            name='Syllabus_Week6',
            field=models.CharField(default='week 6 session', max_length=30, verbose_name='week 6'),
        ),
        migrations.AlterField(
            model_name='courseslist',
            name='Syllabus_Week7',
            field=models.CharField(default='mid-term exam', max_length=30, verbose_name='week 7'),
        ),
        migrations.AlterField(
            model_name='courseslist',
            name='Syllabus_Week8',
            field=models.CharField(default='week 8 session', max_length=30, verbose_name='week 8'),
        ),
        migrations.AlterField(
            model_name='courseslist',
            name='Syllabus_Week9',
            field=models.CharField(default='week 9 session', max_length=30, verbose_name='week 9'),
        ),
    ]
