# Generated by Django 3.2.20 on 2023-08-08 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_courseslist_syllabus_week10_and_more'),
        ('courses', '0008_auto_20230807_1641'),
    ]

    operations = [
    ]
