# Generated by Django 2.2.13 on 2023-07-05 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20230705_0446'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.CharField(default=' ', max_length=10, verbose_name='courseID')),
                ('courseName', models.CharField(default=' ', max_length=20, verbose_name='course name')),
                ('courseDescription', models.TextField(default=' ', verbose_name='course description')),
                ('course_role', models.CharField(choices=[('teacher', 'teacher'), ('student', 'student'), ('teaching assistant', 'teaching assistant')], default='student', max_length=15, verbose_name='course role')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
            options={
                'verbose_name': 'course list',
                'verbose_name_plural': 'course list',
                'ordering': ('courseID',),
            },
        ),
    ]
