# Generated by Django 4.2.2 on 2023-06-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Verification Code')),
                ('email', models.EmailField(max_length=50, verbose_name='Email Address')),
                ('send_type', models.CharField(choices=[('register', 'register'), ('forget', 'forget')], default='register', max_length=10)),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='time')),
            ],
            options={
                'verbose_name': 'email verification code',
                'verbose_name_plural': 'email verification code',
            },
        ),
    ]
