# Generated by Django 3.2.20 on 2023-07-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_nike_name_userprofile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, default='2020-01-01', null=True, verbose_name='birthday'),
        ),
    ]
