# Generated by Django 4.2.2 on 2023-08-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('teacher', 'teacher'), ('student', 'student'), ('admin', 'admin')], default='student', max_length=7, verbose_name='role'),
        ),
    ]
