# Generated by Django 3.2.20 on 2023-07-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselist',
            name='course_role',
            field=models.CharField(choices=[('teacher', 'teacher'), ('student', 'student'), ('teaching assistant', 'teaching assistant')], default='student', max_length=25, verbose_name='course role'),
        ),
        migrations.AlterField(
            model_name='courselist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
