# Generated by Django 3.2.20 on 2023-07-11 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_courselist_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselist',
            name='created_at',
        ),
    ]
