# Generated by Django 3.2.20 on 2023-08-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_courseslist_coursename'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseslist',
            name='Syllabus_Week1',
            field=models.CharField(default='week 1 session', max_length=30, verbose_name='week 1'),
        ),
        migrations.AddField(
            model_name='courseslist',
            name='Syllabus_Week10',
            field=models.CharField(default='week 10 session', max_length=30, verbose_name='week 1'),
        ),
        migrations.AddField(
            model_name='courseslist',
            name='Syllabus_Week11',
            field=models.CharField(default='week 11 session', max_length=30, verbose_name='week 1'),
        ),
        migrations.AddField(
            model_name='courseslist',
            name='Syllabus_Week12',
            field=models.CharField(default='final exam', max_length=30, verbose_name='week 1'),
        ),
        migrations.AddField(
            model_name='courseslist',
            name='Syllabus_Week2',
            field=models.CharField(default='week 2 session', max_length=30, verbose_name='week 1'),
        ),
        migrations.AddField(
            model_name='courseslist',
            name='Syllabus_Week3',
            field=models.CharField(default='week 3 session', max_length=30, verbose_name='week 1'),
        ),
        migrations.AddField(
            model_name='courseslist',
            name='Syllabus_Week4',
            field=models.CharField(default='week 4 session', max_length=30, verbose_name='week 1'),
        ),
        migrations.AddField(
            model_name='courseslist',
            name='Syllabus_Week5',
            field=models.CharField(default='week 5 session', max_length=30, verbose_name='week 1'),
        ),
        migrations.AddField(
            model_name='courseslist',
            name='Syllabus_Week6',
            field=models.CharField(default='week 6 session', max_length=30, verbose_name='week 1'),
        ),
        migrations.AddField(
            model_name='courseslist',
            name='Syllabus_Week7',
            field=models.CharField(default='mid-term exam', max_length=30, verbose_name='week 1'),
        ),
        migrations.AddField(
            model_name='courseslist',
            name='Syllabus_Week8',
            field=models.CharField(default='week 8 session', max_length=30, verbose_name='week 1'),
        ),
        migrations.AddField(
            model_name='courseslist',
            name='Syllabus_Week9',
            field=models.CharField(default='week 9 session', max_length=30, verbose_name='week 1'),
        ),
        migrations.AddField(
            model_name='courseslist',
            name='courseSemester',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Fall', 'Fall'), ('Summer1', 'Summer1'), ('Summer2', 'Summer2')], default='Spring', max_length=10, verbose_name='course semester'),
        ),
        migrations.AddField(
            model_name='courseslist',
            name='courseYear',
            field=models.IntegerField(default=2023, verbose_name='course year'),
        ),
        migrations.AddField(
            model_name='courseslist',
            name='courseZoomlink',
            field=models.CharField(default='https://bu-metcollege.zoom.us/j/97326542525?pwd=b01CcGppWE1HVWY2dHdldDQ4Nk4wZz09#success', max_length=100, verbose_name='course zoom link'),
        ),
    ]
