export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";

export const FETCH_COURSES_START = "FETCH_COURSES_START";
export const FETCH_COURSES_SUCCESS = "FETCH_COURSES_SUCCESS";
export const FETCH_COURSES_FAIL = "FETCH_COURSES_FAIL";

export const GET_USER_ROLE_START = "GET_USER_ROLE_START";
export const GET_USER_ROLE_SUCCESS = "GET_USER_ROLE_SUCCESS";
export const GET_USER_ROLE_FAIL = "GET_USER_ROLE_FAIL";

export const FETCH_USERS_START = "FETCH_USERS_START";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL";

export const COURSE_REGISTER_START = "COURSE_REGISTER_START";
export const COURSE_REGISTER_SUCCESS = "COURSE_REGISTER_SUCCESS";
export const COURSE_REGISTER_FAIL = "COURSE_REGISTER_FAIL";

export const FETCH_ATTENDANCES_START = "FETCH_ATTENDANCES_START";
export const FETCH_ATTENDANCES_SUCCESS = "FETCH_ATTENDANCES_SUCCESS";
export const FETCH_ATTENDANCES_FAIL = "FETCH_ATTENDANCES_FAIL";

export const CREATE_ATTENDANCE_START = "CREATE_ATTENDANCE_START";
export const CREATE_ATTENDANCE_SUCCESS = "CREATE_ATTENDANCE_SUCCESS";
export const CREATE_ATTENDANCE_FAIL = "CREATE_ATTENDANCE_FAIL";

export const FETCH_ATTENDANCE_STUDENT_LIST_START =
  "FETCH_ATTENDANCE_STUDENT_LIST_START";
export const FETCH_ATTENDANCE_STUDENT_LIST_SUCCESS =
  "FETCH_ATTENDANCE_STUDENT_LIST_SUCCESS";
export const FETCH_ATTENDANCE_STUDENT_LIST_FAIL =
  "FETCH_ATTENDANCE_STUDENT_LIST_FAIL";

export const FETCH_COURSE_DETAILS_START = "FETCH_COURSE_DETAILS_START";
export const FETCH_COURSE_DETAILS_SUCCESS = "FETCH_COURSE_DETAILS_SUCCESS";
export const FETCH_COURSE_DETAILS_FAIL = "FETCH_COURSE_DETAILS_FAIL";

export const CREATE_COURSE_START = 'CREATE_COURSE_START';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const CREATE_COURSE_FAIL = 'CREATE_COURSE_FAIL';

export const CREATE_ASSIGNMENT_START = 'CREATE_ASSIGNMENT_START';
export const CREATE_ASSIGNMENT_SUCCESS = 'CREATE_ASSIGNMENT_SUCCESS';
export const CREATE_ASSIGNMENT_FAIL = 'CREATE_ASSIGNMENT_FAIL';

export const FETCH_ASSIGNMENTS_START = 'FETCH_ASSIGNMENTS_START';
export const FETCH_ASSIGNMENTS_SUCCESS = 'FETCH_ASSIGNMENTS_SUCCESS';
export const FETCH_ASSIGNMENTS_FAIL = 'FETCH_ASSIGNMENTS_FAIL';

export const FETCH_ASSIGNMENT_DETAILS_START = 'FETCH_ASSIGNMENT_DETAILS_START';
export const FETCH_ASSIGNMENT_DETAILS_SUCCESS = 'FETCH_ASSIGNMENT_DETAILS_SUCCESS';
export const FETCH_ASSIGNMENT_DETAILS_FAIL = 'FETCH_ASSIGNMENT_DETAILS_FAIL';

export const UPDATE_COURSE_DETAILS_START = 'UPDATE_COURSE_DETAILS_START';
export const UPDATE_COURSE_DETAILS_SUCCESS = 'UPDATE_COURSE_DETAILS_SUCCESS';
export const UPDATE_COURSE_DETAILS_FAIL = 'UPDATE_COURSE_DETAILS_FAIL';
