# Generated by Django 4.2.2 on 2023-07-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_studentsubmissons'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='assignmentID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='courseID',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
