# Generated by Django 4.2.2 on 2023-07-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_assignmentsubmission_assignmentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='assignmentID',
            field=models.IntegerField(),
        ),
    ]
