# Generated by Django 4.2.2 on 2023-07-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_assignmentgrading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentgrading',
            name='grade',
            field=models.FloatField(),
        ),
    ]
