# Generated by Django 3.2.20 on 2023-07-23 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0006_alter_courseslist_coursename'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='attendance', max_length=40, verbose_name='title')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='created date')),
                ('valid_time', models.IntegerField(default=10, verbose_name='valid time interval/min')),
                ('total_number', models.IntegerField(default=1, verbose_name='total number of students')),
                ('attended_number', models.IntegerField(default=1, verbose_name='total number of students')),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseslist')),
            ],
            options={
                'verbose_name': 'attendance list for a course',
                'verbose_name_plural': 'attendance list for a course',
                'ordering': ('courseID',),
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('if_attended', models.BooleanField(default=False, verbose_name='if attended')),
                ('token_key', models.CharField(max_length=10, verbose_name='token for verification')),
                ('attendanceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.attendance')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'attendance record',
                'verbose_name_plural': 'attendance record',
                'ordering': ('attendanceID',),
            },
        ),
    ]
