# Generated by Django 3.2.20 on 2023-07-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attended_number',
            field=models.IntegerField(default=0, verbose_name='total number of students'),
        ),
    ]
